#!/usr/bin/env python3
"""Build theme/shared/icons.css: Steam's solid icons swapped for Lucide outline ones.

    python3 tools/icons.py path/to/lucide-static/icons

Lucide (lucide.dev, ISC licence: theme/LICENSE-Lucide.txt) ships one SVG per icon; the lucide-static
npm package has them all in icons/ (the theme uses v0.460.0). Each icon becomes a data-URI token,
and every Steam icon listed in ICONS below is repainted with it: the svg's own shapes hide, its box
is filled with its text colour (currentColor) and the Lucide drawing is used as a mask. So the new
icon takes the old one's size, colour and focus states.

Only UI icons are swapped (menus, the Quick Access rail and quick settings, the Settings
sidebar, the top bar, page buttons), as Zoe asked; niche ones (game features, comments, friend
list internals, device types) keep Steam's. Most Steam icons have no class, so they're
recognised by the start of their first path's "d" (get it with the inventory script described
in CLAUDE.md). Icons that draw live state (Wi-Fi signal, battery level) aren't listed. Edit the
table, run this, then tools/reload.sh.
"""

import os
import re
import sys
import urllib.parse

# (lucide name, [matchers]). A matcher is either the start of a path's d attribute, or
# "sel:<css selector for the svg>".
ICONS = [
    # Steam menu, Quick Access rail, Settings sidebar
    ("house", ["M32 15V32H22V22H14V32H4V15L1"]),
    ("layout-grid", ["M16 4H4V16H16V4Z"]),
    ("shopping-bag", ["M33.78 19.22L19.22 33.78L4 1", "M33.63 8.05005L30.11 20.81C2"]),
    ("users-round", ["M18 26V31H2V26C2 23.8783 2.8"]),
    ("images", ["M0.111115 0.361084V13.6944H1"]),
    ("download", ["M29 23V27H7V23H2V32H34V23H29Z"]),
    ("settings", ["M33 20.38V15.62L29.07 14.9C2"]),
    ("power", ["M33 18C33.0014 20.7047 32.27"]),
    ("bell", ["M32 24V26H4V24L8 19V12C8 9.3", "M5.37033 3.07108C6.74074 2.1",
              "sel:.header_NotificationsIcon_cieWw > svg"]),
    ("gauge", ["M17.9999 33.0001C26.2841 33."]),
    ("music", ["M31.3191 25.8753C27.1777 33."]),
    ("circle-help", ["M16.48 35.0499V29.3499L16.51"]),
    ("plug", ["M320,32a32,32,0,0,0-64,0v96h"]),
    ("cpu", ["M0 11C0 9.89543 0.895431 9 2"]),
    ("hard-drive", ["M33 19.9286H3L7.35714 6H28.6"]),
    ("bluetooth", ["M29.41 11L16.81 2H14V13.68L8"]),
    ("monitor", ["M34 6H2V28H10.6L9 34H27L25.4"]),
    ("battery-charging", ["M10.9691 29.9823L14.2224 17."]),
    ("volume-2", ["M14.16 6L5.11 13.4H1V23.27H5"]),
    ("gamepad-2", ["M31.5,9.6c-0.3-0.3-0.7-0.6-1",
                   "sel:.appdetailsplaysection_MenuButton_3qDWQ > svg.SVGIcon_BigPicture"]),
    ("keyboard", ["M2 9H34V27H2V9ZM5 13H7V15H5V"]),
    ("palette", ["M10 36.0498H26C26 33.9281 25"]),
    ("accessibility", ["m600 60c-298.03 0-540 241.97"]),
    ("lock", ["M26 16V10C26 7.87827 25.1571"]),
    ("cloud", ["M25.2376 7.0939C26.9019 8.83"]),
    ("layers", ["M27.6606 9H5.44666V22.8569H1"]),
    ("heart-handshake", ["sel:.gamepadpagedsettings_PageListItem_Icon_1F_5Q svg:has(path[d^=\"M11.73 23C9.35238 24.6447 7.\"])"]),
    ("cast", ["M34 6V30H17V26H30V10H6V15H2V"]),
    ("video", ["M35 3H1V33H35V3ZM31.9347 21."]),
    ("wrench", ["M7.3934 28.6067C13.2513 34.4"]),
    ("chevron-down", ["M17.98 26.54L3.20996 11.77H3"]),
    # Quick settings
    ("sun", ["M25 18C25 19.3845 24.5895 20"]),
    ("mic-off", ["M14.6999 25.42L18.0799 22.05"]),
    ("plane", ["M12 10L10 4H14L20 10H12ZM35."]),
    ("wifi", ["M3.55554 28.422C3.56 28.422",
              "sel:.gamepadpagedsettings_PageListItem_Icon_1F_5Q svg:has(path[d^=\"M3 33H10.54\"])"]),
    ("plus", ["M16 34V21H3V16H16V3H21V16H34"]),
    ("moon", ["M14.007 4.16666C14.6626 4.05"]),
    # Game pages, top bar
    ("play", ["M7.5 32.135"]),
    ("search", ["sel:.header_Header_1E_SL :is(.searchbar_SearchIconLeft_2Ya83, .searchbar_SearchIconRight_1Ka4T)"]),
]


def svg_uri(path):
    src = open(path).read()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", src, re.S).group(1)
    inner = " ".join(inner.split()).replace("\"", "'").replace(" />", "/>")
    svg = ("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='black' "
           "stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>" + inner + "</svg>")
    return "url(\"data:image/svg+xml," + urllib.parse.quote(svg, safe=" /:=',.-") + "\")"


def selector(m):
    return m[4:] if m.startswith("sel:") else 'svg:has(path[d^="%s"])' % m


def main(lucide_dir, out):
    tokens, every, rules = [], [], []
    for name, matchers in ICONS:
        tokens.append("  --zdt-icon-%s: %s;" % (name, svg_uri(os.path.join(lucide_dir, name + ".svg"))))
        sels = [selector(m) for m in matchers]
        every += sels
        rules.append(":is(%s):not(#zdt) {\n  mask-image: var(--zdt-icon-%s);\n}" % (", ".join(sels), name))
    allsel = ",\n".join(every)
    css = """/* Zoe's Deck Theme: outline icons. GENERATED by tools/icons.py; edit the table there.

   Steam's solid glyphs are swapped for rounded Lucide outlines (lucide.dev, ISC licence:
   LICENSE-Lucide.txt). Each Steam icon is recognised by its drawing; its own shapes hide and its
   box is filled with its text colour through a mask of the Lucide icon, so the new icon keeps the
   old one's size, colour and focus states. */

:root {
%s
}

:is(
%s
):not(#zdt) {
  background: currentColor;
  mask-position: center;
  mask-size: contain;
  mask-repeat: no-repeat;
}

:is(
%s
) > * {
  display: none;
}

%s
""" % ("\n".join(tokens), allsel, allsel, "\n\n".join(rules))
    open(out, "w").write(css)
    print("wrote %s: %d icons, %d Steam glyphs" % (out, len(ICONS), len(every)))


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    main(sys.argv[1], os.path.join(here, "..", "theme", "shared", "icons.css"))
